import { Injectable, Inject } from '@nestjs/common';
import type { IEmailService } from 'src/shared/services/email/interfaces/iemail.service';
import type { IEmailOtpRepository } from '../../../domain/repositories/iemail-otp.repository';
import { ISendEmailOtpUseCase } from '../../interfaces/otp/otp-use-case.interface';
import { EmailOtpEntity } from '../../../domain/entities/email-otp.entity';
import { SendEmailOtpInput } from 'src/shared/types/company/otp/send-email-otp-input.type';
import type { IOtpService } from 'src/shared/services/auth/interfaces/iotp.service';

@Injectable()
export class SendEmailOtpUseCase implements ISendEmailOtpUseCase {
  constructor(
    @Inject('IEmailOtpRepository')
    private readonly _emailOtpRepository: IEmailOtpRepository,

    @Inject('IEmailService')
    private readonly _emailService: IEmailService,

    @Inject('IOtpService')
    private readonly _otpService: IOtpService,
  ) { }

  async execute(input: SendEmailOtpInput): Promise<void> {
    const otp = this._otpService.generateOtp();
    const otpHash = await this._otpService.hashOtp(otp);
    const expiresAt = this._otpService.getExpiryDate();

    console.log(
      `📧 Sending OTP to: ${input.email} | Purpose: ${input.purpose} | OTP: ${otp}`,
    );

    const otpEntity = new EmailOtpEntity(
      "", // ID will be generated by DB
      input.userId,
      input.email,
      otpHash,
      expiresAt,
      false,
      new Date(),
      input.newEmail,
      input.purpose,
    );

    await this._emailOtpRepository.create(otpEntity);
    await this._emailService.sendOtp(input.email, otp);
  }
}
