import { Injectable, Inject, BadRequestException } from '@nestjs/common';
import * as bcrypt from 'bcrypt';
import type { PendingRegistrationRepository } from '../../../domain/repositories/cache/auth-repository/pending-registration.repository';
import type { UserRepository } from '../../../domain/repositories/user.repository';
import { UserEntity } from '../../../domain/entities/user.entity';
import { VerifyEmailOtpInput } from 'src/shared/types/company/otp/verify-email-otp-input.type';
import { UserStatus } from 'src/shared/enums/user/user-status.enum';
import { OTP_MESSAGES } from 'src/shared/constants/messages/otp/otp.messages';
import { UserRole } from 'src/shared/enums/user/user-role.enum';

@Injectable()
export class VerifyEmailOtpUseCase {
  constructor(
    @Inject('PendingRegistrationRepository')
    private readonly _pendingRepository: PendingRegistrationRepository,

    @Inject('UserRepository')
    private readonly _userRepository: UserRepository,
  ) { }

  async execute(input: VerifyEmailOtpInput) {
    const pending = await this._pendingRepository.find(input.email);
    if (!pending) {
      throw new BadRequestException(OTP_MESSAGES.OTP_EXPIRED);
    }

    // Enforce expiry
    if (new Date(pending.expiresAt) < new Date()) {
      throw new BadRequestException(OTP_MESSAGES.OTP_EXPIRED);
    }

    // Secure OTP check
    const isValid = await bcrypt.compare(input.otp, pending.otpHash);
    if (!isValid) {
      throw new BadRequestException(OTP_MESSAGES.OTP_INVALID);
    }

    const userEntity = new UserEntity(
      "", // ID will be generated by DB
      pending.admin.firstName,
      pending.admin.lastName,
      pending.admin.email.toLowerCase(),
      UserRole.COMPANY_ADMIN,
      pending.admin.phone,
      pending.admin.password,
      UserStatus.ACTIVE,
      new Date(),
      new Date(),
      undefined, // companyId
      undefined, // department
      undefined, // inviteStatus
      true,      // hasPassword
      undefined, // dateOfBirth
      undefined, // gender
      undefined, // maritalStatus
      undefined, // nationality
      undefined, // bloodGroup
      undefined, // timeZone
      undefined, // bio
      undefined, // streetAddress
      undefined, // city
      undefined, // state
      undefined, // country
      undefined, // zipCode
      undefined, // emergencyContactName
      undefined, // emergencyContactPhone
      undefined, // emergencyContactRelation
      undefined, // linkedInUrl
      undefined, // personalWebsite
      undefined, // profileImageUrl
      undefined, // profileImagePublicId
      [],        // skills
      false,     // isOnboarded
    );

    const createdUser = await this._userRepository.create(userEntity);

    // Clear Redis
    await this._pendingRepository.delete(input.email);

    return {
      user: {
        id: createdUser.id,
        email: createdUser.email,
        role: createdUser.role,
        isOnboarded: createdUser.isOnboarded,
      },
    };
  }
}
