import { Injectable, Inject, BadRequestException } from '@nestjs/common';
import * as bcrypt from 'bcrypt';
import type { IPendingRegistrationRepository } from '../../../domain/repositories/cache/auth-repository/ipending-registration.repository';
import type { IUserRepository } from '../../../domain/repositories/iuser.repository';
import type { IJwtService } from 'src/shared/services/auth/interfaces/ijwt.service';
import { IVerifyEmailOtpUseCase } from '../../interfaces/otp/otp-use-case.interface';
import { UserStatus } from 'src/shared/enums/user/user-status.enum';
import { UserRole } from 'src/shared/enums/user/user-role.enum';
import { UserEntity } from '../../../domain/entities/user.entity';
import { AUTH_MESSAGES } from 'src/shared/constants/messages/auth/auth.messages';
import { OTP_MESSAGES } from 'src/shared/constants/messages/otp/otp.messages';
import type { IOtpService } from 'src/shared/services/auth/interfaces/iotp.service';
import { VerifyEmailOtpDto } from '../../dto/verify-email-otp.dto';

@Injectable()
export class VerifyEmailOtpUseCase implements IVerifyEmailOtpUseCase {
  constructor(
    @Inject('IPendingRegistrationRepository')
    private readonly _pendingRepository: IPendingRegistrationRepository,

    @Inject('IUserRepository')
    private readonly _userRepository: IUserRepository,

    @Inject('IJwtService')
    private readonly _jwtService: IJwtService,

    @Inject('IOtpService')
    private readonly _otpService: IOtpService,
  ) { }

  async execute(input: VerifyEmailOtpDto) {
    const pending = await this._pendingRepository.find(input.email);
    if (!pending) {
      throw new BadRequestException(OTP_MESSAGES.OTP_EXPIRED);
    }

    // Enforce expiry
    if (new Date(pending.expiresAt) < new Date()) {
      throw new BadRequestException(OTP_MESSAGES.OTP_EXPIRED);
    }

    // Secure OTP check
    const isValid = await bcrypt.compare(input.otp, pending.otpHash);
    if (!isValid) {
      throw new BadRequestException(OTP_MESSAGES.OTP_INVALID);
    }

    const userEntity = new UserEntity(
      "", // ID will be generated by DB
      pending.admin.firstName,
      pending.admin.lastName,
      pending.admin.email.toLowerCase(),
      UserRole.COMPANY_ADMIN,
      pending.admin.phone,
      pending.admin.password,
      UserStatus.ACTIVE,
      new Date(),
      new Date(),
      undefined, // companyId
      undefined, // department
      undefined, // inviteStatus
      true,      // hasPassword
      undefined, // dateOfBirth
      undefined, // gender
      undefined, // maritalStatus
      undefined, // nationality
      undefined, // bloodGroup
      undefined, // timeZone
      undefined, // bio
      undefined, // streetAddress
      undefined, // city
      undefined, // state
      undefined, // country
      undefined, // zipCode
      undefined, // emergencyContactName
      undefined, // emergencyContactPhone
      undefined, // emergencyContactRelation
      undefined, // linkedInUrl
      undefined, // personalWebsite
      undefined, // profileImageUrl
      undefined, // profileImagePublicId
      [],        // skills
      false,     // isOnboarded
    );

    const createdUser = await this._userRepository.create(userEntity);

    // Generate Tokens
    const accessToken = await this._jwtService.generateAccessToken({
      userId: createdUser.id,
      role: createdUser.role,
      companyId: createdUser.companyId,
    });

    const refreshToken = await this._jwtService.generateRefreshToken({
      userId: createdUser.id,
    });

    // Clear Redis
    await this._pendingRepository.delete(input.email);

    return {
      accessToken,
      refreshToken,
      user: {
        id: createdUser.id,
        email: createdUser.email,
        role: createdUser.role,
        isOnboarded: createdUser.isOnboarded,
      },
    };
  }
}
