import { Injectable, Inject, ConflictException } from '@nestjs/common';
import type { ICreateSubscriptionPlanUseCase } from '../interfaces/subscription-plan.use-case.interface';
import type { ISubscriptionPlanRepository } from '../../domain/repositories/isubscription-plan.repository';
import { CreateSubscriptionPlanDto } from '../dtos/create-subscription-plan.dto';
import { SubscriptionPlanEntity } from '../../domain/entities/subscription-plan.entity';

@Injectable()
export class CreateSubscriptionPlanUseCase implements ICreateSubscriptionPlanUseCase {
  constructor(
    @Inject('ISubscriptionPlanRepository')
    private readonly _subscriptionPlanRepository: ISubscriptionPlanRepository,
  ) {}

  async execute(dto: CreateSubscriptionPlanDto): Promise<SubscriptionPlanEntity> {
    const existingPlan = await this._subscriptionPlanRepository.findByName(dto.name);
    if (existingPlan) {
      throw new ConflictException(`Subscription plan with name ${dto.name} already exists`);
    }

    const plan = new SubscriptionPlanEntity(
      '', // ID will be generated by persistence layer
      dto.name,
      dto.type,
      dto.price,
      dto.description,
      dto.features,
      dto.isActive,
    );

    return this._subscriptionPlanRepository.create(plan);
  }
}
