export const industryOptionsData = [
    "Information Technology",
    "Software Development",
    "Web Development",
    "Mobile App Development",
    "Cloud Computing",
    "Cybersecurity",
    "Data Science & Analytics",
    "Artificial Intelligence & Machine Learning",
    "IT Services & Consulting",
    "DevOps & Infrastructure",
    "Networking & Systems Administration",
    "Enterprise Software (ERP, CRM)",
    "Gaming & Interactive Media",
    "Blockchain & Web3",
    "E-commerce Technology",
    "IT Support & Managed Services",
    "Other",
  ];