# Base
FROM node:26-alpine AS base

WORKDIR /app

RUN npm install -g pnpm@10.12.4

COPY package.json pnpm-lock.yaml ./

# Dependencies
FROM base AS deps

RUN pnpm install --frozen-lockfile

# Build
FROM base AS build

COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_RAZORPAY_KEY_ID
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_RAZORPAY_KEY_ID=$NEXT_PUBLIC_RAZORPAY_KEY_ID

RUN pnpm build

# Production
FROM node:26-alpine AS production

WORKDIR /app

RUN npm install -g pnpm@10.12.4

ENV NODE_ENV=production

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --prod --frozen-lockfile

COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
COPY --from=build /app/public ./public

EXPOSE 3000

CMD ["node", "server.js"]