services:
  backend:
    image: nidhintech/nexus-backend:latest
    command: pnpm run start
    env_file:
      - ./backend/.env
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "4000:4000"

  frontend:
    image: nidhintech/nexus-frontend:latest
    command: pnpm start
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    ports:
      - "3000:3000"
  
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    