services:
  frontend:
    build:
      context: ./frontend
      target: deps
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    env_file:
      - ./frontend/.env
    command: pnpm dev
    depends_on:
      - backend

  backend:
    image: node:22
    working_dir: /app
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./backend/.env
    command: sh -c "corepack enable && corepack prepare pnpm@10.12.4 --activate && pnpm install && pnpm exec nest start --watch"
    tty: true
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"