# Base
FROM node:26-alpine AS base

WORKDIR /app

RUN npm install -g pnpm@10.12.4

COPY package.json pnpm-lock.yaml ./

# Dependencies
FROM base AS deps

RUN pnpm install --frozen-lockfile

# Build
FROM base AS build

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN pnpm run build

# Production
FROM node:26-alpine AS production

WORKDIR /app

RUN npm install -g pnpm@10.12.4

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --prod --frozen-lockfile

COPY --from=build /app/dist ./dist

EXPOSE 4000

CMD ["pnpm", "run", "start"]