import { Injectable, Inject, ForbiddenException } from '@nestjs/common';
import { isValidObjectId } from 'mongoose';
import type { IUserRepository } from 'src/modules/auth/domain/repositories/iuser.repository';
import type { ICompanyRepository } from 'src/modules/auth/domain/repositories/icompany.repository';
import type { IJwtService } from 'src/shared/services/interfaces/ijwt.service';
import { ISocialLoginUseCase } from '../../interfaces/auth-use-cases.interfaces';
import { UserStatus } from 'src/shared/enums/user/user-status.enum';
import { UserRole } from 'src/shared/enums/user/user-role.enum';
import { CompanyStatus } from 'src/shared/enums/company/company-status.enum';
import { UserEntity } from 'src/modules/auth/domain/entities/user.entity';
import { AUTH_MESSAGES } from 'src/shared/constants/messages/auth/auth.messages';
import {
  SocialLoginInput,
  SocialLoginResponse,
} from 'src/shared/types/auth/social-login.type';

@Injectable()
export class SocialLoginUseCase implements ISocialLoginUseCase {
  constructor(
    @Inject('IUserRepository')
    private readonly _userRepository: IUserRepository,
    @Inject('ICompanyRepository')
    private readonly _companyRepository: ICompanyRepository,
    @Inject('IJwtService')
    private readonly _jwtService: IJwtService,
  ) { }

  async execute(input: SocialLoginInput): Promise<SocialLoginResponse> {
    const { email, firstName, lastName, provider, providerId } = input;
    let user = await this._userRepository.findByEmail(email.toLowerCase());

    console.log('-----------------------------------------');
    console.log(' SOCIAL LOGIN/REGISTER USE CASE');
    console.log(' Email:', email);
    console.log(' User Found:', !!user);

    if (!user) {
      console.log(' User NOT found - Creating new account...');
      const newUser = new UserEntity(
        "", // ID generated by DB
        firstName,
        lastName,
        email.toLowerCase(),
        UserRole.COMPANY_ADMIN,
        "", // Phone
        undefined, // No password hash
        UserStatus.ACTIVE,
        new Date(),
        new Date(),
        undefined, // No companyId yet
        undefined, // No department
        undefined, // No inviteStatus
        false, // hasPassword false for social users initially
        undefined, undefined, undefined, undefined, undefined, undefined, undefined,
        undefined, undefined, undefined, undefined, undefined,
        undefined, undefined, undefined,
        undefined, undefined,
        undefined, undefined,
        [], // skills
        false, // isOnboarded false
        provider,
        providerId
      );

      user = await this._userRepository.create(newUser);
      console.log(' New User Created:', JSON.stringify(user, null, 2));
    } else {
      console.log(' User Found - ID:', user.id);
      console.log(' Role:', user.role);
      console.log(' IsOnboarded:', user.isOnboarded);
      console.log(' Company ID:', user.companyId);
    }
    console.log('-----------------------------------------');

    if (user.status === UserStatus.SUSPENDED) {
      throw new ForbiddenException(AUTH_MESSAGES.USER_BLOCKED);
    }

    if (user.status !== UserStatus.ACTIVE) {
      throw new ForbiddenException(AUTH_MESSAGES.ACCOUNT_NOT_ACTIVE);
    }

    // Check company suspension ONLY IF onboarded
    if (user.isOnboarded) {
      await this.checkCompanySuspension(user.companyId);
    }

    const accessToken = this._jwtService.generateAccessToken({
      userId: user.id,
      role: user.role,
      companyId: user.companyId,
    });

    const refreshToken = this._jwtService.generateRefreshToken({
      userId: user.id,
    });

    if (user.role === UserRole.COMPANY_ADMIN && !user.isOnboarded) {
      console.log(' SocialLogin: User NOT onboarded, returning tokens for onboarding redirect');
      return {
        accessToken,
        refreshToken,
        user: {
          id: user.id,
          email: user.email,
          firstName: user.firstName,
          lastName: user.lastName,
          role: user.role,
          isOnboarded: false,
        },
      };
    }

    console.log(' SocialLogin: User onboarded, issuing tokens');
    return {
      accessToken,
      refreshToken,
      user: {
        id: user.id,
        email: user.email,
        firstName: user.firstName,
        lastName: user.lastName,
        role: user.role,
        companyId: user.companyId,
        isOnboarded: user.role === UserRole.COMPANY_ADMIN ? user.isOnboarded : true,
      },
    };
  }

  private async checkCompanySuspension(
    companyId: string | undefined,
  ): Promise<void> {
    if (!companyId || !isValidObjectId(companyId)) return;

    const company = await this._companyRepository.findById(companyId);

    if (company?.status === CompanyStatus.SUSPENDED) {
      throw new ForbiddenException(AUTH_MESSAGES.COMPANY_SUSPENDED);
    }
  }
}
