import { InviteStatus } from "src/shared/enums/user/user-invite-status.enum";

export class Employee {
  constructor(
    public readonly id: string,
    public readonly name: string,
    public readonly email: string,
    public readonly role: string,
    public readonly department: string,
    public readonly phone: string,
    public readonly isActive: boolean,
    public readonly hasPassword: boolean,
    public readonly inviteStatus: InviteStatus,
    public readonly companyId?: string,
    public readonly avatar?: string,
    public readonly joinDate?: string,
    public readonly skills?: string[],
    public readonly documents?: any[],
    public readonly bio?: string,
    public readonly bloodGroup?: string,
    public readonly gender?: string,
    public readonly nationality?: string,
    public readonly maritalStatus?: string,
    public readonly linkedInUrl?: string,
    public readonly personalWebsite?: string,
    public readonly timeZone?: string,
    public readonly streetAddress?: string,
    public readonly city?: string,
    public readonly state?: string,
    public readonly zipCode?: string,
    public readonly country?: string,
    public readonly emergencyContactName?: string,
    public readonly emergencyContactPhone?: string,
    public readonly emergencyContactRelation?: string,
  ) { }
}
