import { Injectable, Inject, BadRequestException } from '@nestjs/common';
import type { IAttendanceRepository } from '../../domain/repositories/iattendance.repository';
import { IClockInUseCase } from '../interfaces/attendance-use-cases.interface';
import { AttendanceEntity, AttendanceActivityEntity } from '../../domain/entities/attendance.entity';
import { ClockInDto } from '../dto/clock-in.dto';

@Injectable()
export class ClockInUseCase implements IClockInUseCase {
  constructor(
    @Inject('IAttendanceRepository')
    private readonly _attendanceRepository: IAttendanceRepository,
  ) {}

  async execute(userId: string, companyId: string, dto: ClockInDto): Promise<AttendanceEntity> {
    const now = new Date();
    const dateStr = now.toISOString().split('T')[0]; // "YYYY-MM-DD"

    // Check if user already has an active or completed record for today
    const existing = await this._attendanceRepository.findByUserAndDate(userId, dateStr);
    if (existing) {
      if (existing.status === 'COMPLETED') {
        throw new BadRequestException('You have already clocked out for today.');
      }
      throw new BadRequestException('You are already clocked in.');
    }

    const activity = new AttendanceActivityEntity(
      'CLOCK_IN',
      null,
      now,
      dto.remarks
    );

    const newAttendance = new AttendanceEntity(
      '', // ID is generated by database persistence mapper
      userId,
      companyId,
      dateStr,
      'WORKING',
      now,
      null,
      [activity],
      0,
      0
    );

    return this._attendanceRepository.create(newAttendance);
  }
}
